- name: install fish
  homebrew:
    name: fish
    state: present
- name: Get Fish shell installation path
  command: "which fish"
  register: fish_install_path_result
  changed_when: false
  check_mode: no
- name: Set Fish shell as default shell for the user
  lineinfile:
    dest: /etc/shells
    line: "{{ fish_install_path_result.stdout }}"
    state: present
    insertafter: EOF
- name: Change the default shell for the user to Fish
  command: "chsh -s {{ fish_install_path_result.stdout }}"
- name: Ensure Fish configuration directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: directory
- name: Copy Fish config file to the user's home directory
  copy:
    src: files/.config/fish/config.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    mode: '0644'
- name: Copy Fish functions to the user's home directory
  copy:
    src: files/.config/fish/functions
    dest: "{{ ansible_env.HOME }}/.config/fish/functions"
    mode: '0644'
- name: Touch custom Fish configuration file
  file:
    path: "{{ ansible_env.HOME }}/.config/fish/custom_config.fish"
    state: touch
