---
- name: Create Kitty config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/kitty"
    state: directory
    mode: 0755

- name: Install Kitty config files
  copy:
    src: ".config/kitty/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/kitty/{{ item }}"
    mode: 0644
  loop:
    - "macos-launch-services-cmdline"
    - "kitty.conf"
